version: '3.8'

services:
  # Banco de dados SQL Server
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: yeti-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - yeti-network

  # Backend API
  backend:
    build: .
    container_name: yeti-backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=dbBiblioteca;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true;MultipleActiveResultSets=true
      - JwtSettings__SecretKey=MinhaChaveSecretaSuperSeguraParaJWT2025
      - JwtSettings__Issuer=Projeto2025API
      - JwtSettings__Audience=Projeto2025API
      - JwtSettings__ExpirationHours=8
    ports:
      - "5072:80"
    depends_on:
      - sqlserver
    networks:
      - yeti-network

  # Frontend
  frontend:
    build: ./frontend-yeti
    container_name: yeti-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - yeti-network

volumes:
  sqlserver_data:


networks:
  yeti-network:
    driver: bridge


